services:
  app:
    build:
      context: .
      network: host
    ports:
      - "8000:8000"
    volumes:
      - ./todo.db:/app/todo.db
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --workers 2
    restart: unless-stopped